Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/core/urls.py
from django.urls import path
from core.views import *

urlpatterns = [
    path('', home, name='home'),
    path('products/', mostrar_productos, name='products'),
    path('logout/', exit, name='exit'),
    path('login/', login_request, name = 'login'),
    path('register/', register, name = 'register'),
    path('avatar/', agregar_avatar, name= "agregar_avatar"),
    path('accounts/profile/', profile, name= "perfil"),
    path('accounts/editarperfil/', editarPerfil, name="editarperfil"),
    
]

Blog/core/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
# Create your models here.

class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="media")

    def __str__(self):
        return self.nombre

Blog/core/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'last_name', 'first_name', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class AvatarFormulario(forms.Form):
    imagen = forms.ImageField()


class UserEditForm(UserChangeForm):
    
    email = forms.EmailField(label="Ingrese su email:")
    last_name = forms.CharField(label='Apellido')
    first_name = forms.CharField(label='Nombre')
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email', 'last_name', 'first_name']

Blog/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login, authenticate
from core.forms import *
from core.models import *
# Create your views here.
def home(request):
    return render(request, "core/home.html")

#@login_required
def products(request):
    return render(request, "core/products.html")

def exit(request):
    logout(request)
    return redirect('home')

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')

            user = authenticate(username=usuario, password=contra)

            if user is not None:
                login(request,user)

                return render(request,"core/home.html", {"mensaje":f"Bienvenido{usuario}"})
            else:
                return render(request,"core/home.html", {"mensaje":"Error, datos incorrectos"})
        else:
            return render(request,"core/home.html", {"mensaje":"Error, formulario erroneo"})
        
    form = AuthenticationForm()

    return render(request,"core/login.html", {'form':form})

def register(request):
    
    if request.method == 'POST':
         
        #form = UserCreationForm(request.POST)
        form = UserRegisterForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            form.save()
            return render(request, "core/home.html" , {"mensaje":"Usuario Creado :)"})
        
    else:
        
        #form = UserCreationForm()
        form = UserRegisterForm()

    return render(request,"core/registro.html" , {"form":form})

@login_required
def agregar_avatar(request):
    if request.method == 'POST':
         
        formulario = AvatarFormulario(request.POST, request.FILES)

        if formulario.is_valid():

            info = formulario.cleaned_data

            usuario_actual = User.objects.get(username=request.user)
            nuevo_avatar = Avatar(usuario=usuario_actual, imagen=info ["imagen"])

            nuevo_avatar.save()
            return render(request, "core/home.html" , {"mensaje":"Avatar Creado :)"})
        
    else:
        
        formulario = AvatarFormulario()


    return render(request,"core/nuevo_avatar.html" , {"formu":formulario})

@login_required
def mostrar_productos(request):
    print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
    productos = Producto.objects.all()
    return render(request, "core/products.html", {"productos": productos})

def profile(request):
    return render(request, "core/perfil.html")

@login_required
def editarPerfil(request):

    usuario = request.user

    if request.method == 'POST':

        miFormulario = UserEditForm(request.POST)

        if miFormulario.is_valid():

            informacion = miFormulario.cleaned_data

            usuario.username = informacion['username']
            usuario.email = informacion['email']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']
            usuario.set_password = informacion["password1"]

            usuario.save()

            return render(request, "core/home.html")

    else:

        miFormulario = UserEditForm(initial={'email': usuario.email, 'username': usuario.username, 'first_name': usuario.first_name, 'last_name': usuario.last_name})

    return render(request, "core/editarperfil.html", {"form":miFormulario})

Blog/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicación</title>
</head>
<body>
    <h2>Inicio</h2>
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href={% url 'home'%}>Inicio</a></li>
                                 
            {% if request.user.is_authenticated %}
                <!-- <a class="navbar-brand" href={% url 'products'%}>Productos</a></li> -->
                <a class="navbar-brand" href="{% url 'products' %}">Productos</a>
                <a class="navbar-brand" href={% url 'agregar_avatar'%}>Avatar</a></li>
                <a class="navbar-brand" href={% url 'perfil'%}>Perfil</a></li>
                <a class="navbar-brand" href={% url 'editarperfil'%}>Editar Perfil</a></li>
                <a class="navbar-brand" href={% url 'exit'%}>Salir</a></li>
                <img src="{{user.avatar_set.last.imagen.url}}" width="30px" height="30px" alt="No fué posible cargar la imágen del avatar">               
                
            {% else %}
                <a class="navbar-brand" href={% url 'login'%}>Ingresar</a></li>
                <a class="navbar-brand" href={% url 'register'%}>Registrarse</a></li>
                
            {% endif %}
    </ul>

    {% block content %}{% endblock %}

</body>
</html>

Blog/core/templates/core/editarperfil.html
{% extends 'core/base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Perfil</title>
</head>
<body>

    <form action="" method="POST">{% csrf_token %}

        {{form.as_p}}

        <button type="submit">Editar</button>

    </form>
    
</body>
{% endblock %}
</html>

Blog/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}

<h3>Inicio</h3>
{% if request.user.is_authenticated %}
    
    <hr>
    <h4>
        {{user.username | upper}}, Bienvenido
    </h4>
{% endif %}
{% endblock %}

Blog/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block content %}

<h3>Login</h3>

<br>

<form action="" method="post">
    {% csrf_token %}

    <input type="text" name="username" id="" placeholder="Nombre de Usuario">
    <br>
    <input type="password" name="password" id="" placeholder="Contraseña">

    <br>
    <button type="submit">Iniciar Sesión</button>




</form>

{% endblock %}

Blog/core/templates/core/nuevo_avatar.html
<!DOCTYPE html>
<html lang="en">
{% extends 'core/base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Avatar</title>
</head>
<body>

    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

        

        {{formu}}

        
        <button type="submit">Crear Avatar</button>

    </form>
    
    {% endblock %}
    
</body>

</html>

Blog/core/templates/core/perfil.html
{% extends 'core/base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>
</head>
<body>
    <p>Nombre de usuario: {{ user.username }}</p>
    <p>Nombre: {{user.first_name}}</p>
    <p>Apellido: {{user.last_name}}</p>
    <p>Email: {{ user.email }}</p>
    <p>Avatar: <img src="{{user.avatar_set.last.imagen.url}}" width="30px" height="30px" alt="No fué posible cargar la imágen del avatar"></p>
    

    
    
    {% endblock %}
    
</body>

Blog/core/templates/core/products.html
{% extends 'core/base.html' %}

{% block content %}

<h3>Productos</h3>



{% for producto in productos %}
<div class="producto">
    <h4>{{ producto.nombre }}</h4>
    <img src="{{ producto.imagen.url }}" alt="Imagen del Producto">
</div>
{% endfor %}

{% endblock %}

Blog/core/templates/core/registro.html
{% extends 'core/base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>

    <form action="" method="POST">

        {% csrf_token %}

        {{form.as_p}}

        
        <button type="submit">Registrarse</button>

    </form>
    
</body>
{% endblock %}
</html>